# Generated by Django 5.1.7 on 2025-04-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
