# Generated by Django 5.1.7 on 2025-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_delete_departments_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_dob', models.DateTimeField()),
                ('student_gender', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=255, unique=True)),
                ('student_graduating_class', models.IntegerField()),
                ('student_phone_number', models.CharField(max_length=20)),
                ('student_specialization', models.CharField(max_length=255)),
                ('student_is_active', models.BooleanField(default=True)),
                ('student_school', models.CharField(max_length=50)),
            ],
        ),
    ]
