# Generated by Django 5.1.7 on 2025-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='useremail',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
