# Generated by Django 5.1.7 on 2025-04-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_userlogin_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='useremail',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
