# Generated by Django 5.1.7 on 2025-05-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0017_alter_enrollment_grade'),
        ('GiaoVienApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.enrollment'),
        ),
    ]
