# Generated by Django 5.1.7 on 2025-05-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GiaoVienApp', '0002_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
