# Generated by Django 5.1.7 on 2025-05-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0017_alter_enrollment_grade'),
        ('GiaoVienApp', '0003_delete_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.enrollment')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='GiaoVienApp.attendancesession')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.student')),
            ],
            options={
                'db_table': 'attendance_record',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
