# Generated by Django 5.1.7 on 2025-12-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_school',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
