# Generated by Django 5.1.7 on 2026-01-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_student_student_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='registration',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
