# Generated by Django 5.1.7 on 2025-05-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classstudent',
        ),
    ]
