# Generated by Django 5.1.7 on 2025-05-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent_firstname',
            new_name='parent_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parent_address',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parent_lastname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parent_relationship_to_student',
        ),
    ]
