# Generated by Django 5.1.7 on 2025-04-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=50)),
                ('relatedid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userlogin',
            },
        ),
    ]
