# Generated by Django 5.1.7 on 2025-05-19 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_rename_parent_firstname_parent_parent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='DBApp.class')),
            ],
            options={
                'db_table': 'class_timetable',
            },
        ),
    ]
