# Generated by Django 5.1.7 on 2025-05-13 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_delete_classstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classstudent',
            fields=[
                ('connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_field', models.OneToOneField(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='DBApp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DBApp.student')),
            ],
            options={
                'db_table': 'classstudent',
                'unique_together': {('class_field', 'student')},
            },
        ),
    ]
