# Generated by Django 5.1.7 on 2025-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_classstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_semester', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
