# Generated by Django 5.1.7 on 2025-04-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_userlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={'managed': False},
        ),
    ]
