# Generated by Django 5.1.7 on 2025-05-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_remove_class_end_time_remove_class_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTimetable',
        ),
    ]
