# Generated by Django 5.1.7 on 2025-04-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0004_alter_userlogin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userlogin',
        ),
    ]
