# Generated by Django 5.1.7 on 2025-05-13 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_final_coeff',
            field=models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='course_midterm_coeff',
            field=models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
