# Generated by Django 5.1.7 on 2025-05-13 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0005_course_course_final_coeff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudent',
            name='class_field',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='DBApp.class'),
        ),
    ]
