# Generated by Django 5.1.7 on 2025-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0005_classtimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
