# Generated by Django 5.1.7 on 2025-05-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0006_alter_classstudent_class_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='score',
        ),
    ]
