# Generated by Django 5.1.7 on 2025-05-13 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0007_remove_assignment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmentscore',
            fields=[
                ('connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.assignment')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.student')),
            ],
            options={
                'db_table': 'assignment_score',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
