# Generated by Django 5.1.7 on 2025-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignmentscore',
        ),
    ]
