# Generated by Django 5.1.7 on 2025-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0008_assignmentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='day_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
