# Generated by Django 5.1.7 on 2025-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0009_alter_assignment_day_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='withdrawal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
