# Generated by Django 5.1.7 on 2025-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0009_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(default=3),
        ),
    ]
