# Generated by Django 5.1.7 on 2025-05-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0010_course_course_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
