# Generated by Django 5.1.7 on 2025-05-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0011_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classstudent',
        ),
    ]
