# Generated by Django 5.1.7 on 2025-05-22 01:22

import DBApp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0011_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField(blank=True, max_length=10000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=DBApp.models.work_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('day_uploaded', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.assignment')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.class')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.student')),
            ],
            options={
                'db_table': 'work',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
