# Generated by Django 5.1.7 on 2025-05-14 14:12

import DBApp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0012_delete_classstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField(blank=True, max_length=10000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=DBApp.models.work_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('day_uploaded', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.assignment')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.student')),
            ],
            options={
                'db_table': 'work',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
