# Generated by Django 5.1.7 on 2025-05-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0012_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
