# Generated by Django 5.1.7 on 2025-05-14 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0013_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
