# Generated by Django 5.1.7 on 2025-05-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0014_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'class_field')},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
    ]
