# Generated by Django 5.1.7 on 2025-05-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0014_work_score_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_bug', models.TextField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.class')),
            ],
            options={
                'db_table': 'attendance_session',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.student')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='DBApp.attendancesession')),
            ],
            options={
                'db_table': 'attendance_record',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
