# Generated by Django 5.1.7 on 2025-11-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0015_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set(),
        ),
    ]
