# Generated by Django 5.1.7 on 2025-05-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0015_report_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='class_field',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
