# Generated by Django 5.1.7 on 2025-05-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0017_alter_enrollment_grade'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sender',
            field=models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='Login.userlogin'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
