# Generated by Django 5.1.7 on 2025-05-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0018_report_sender_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
