# Generated by Django 5.1.7 on 2025-05-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0019_semester'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semester',
            table='semester',
        ),
    ]
