from .studentAPI import *
from .teacherAPI import *
from .classAPI import *
from .authAPI import *
from .enrollmentAPI import *
from .courseAPI import *
from .semesterAPI import *
from .assignmentAPI import *
from .miscAPI import *